### PR TITLE
Generate `@safeps` modules with wrapped runtime type checked functions

### PR DESCRIPTION
**Pull request by drathier**
Also generate @safeps files where all functions are runtime typesafe to call into from erlang/elixir. 

It currently supports these types:
```
- integer
- float
- boolean
- binary (utf-8 string)
- array of any supported type
- map of fixed shape (purescript records)
```
Notable currently missing types:
```
- Foreign
- ADT's (out of scope for now, can be added later if adt is exported, which is what we want anyway I think)
```

If a decl uses a type we don't know how to type-check yet, it won't be included in the `@safeps` module. You can still call the function in the `@ps` module like before.

Sample of generated type-safety code:
```
      case _@46 of
        (_@46) when (erlang:is_binary(_@46)) -> typecheck
      end,
      case _@47 of
        (#{wooo:=_@48, yay:=_@49, abc:=_@50}) when (erlang:map_size(_@47)) == 3 -> begin
          case _@48 of
            (#{wint:=_@51, wont:=_@52}) when (erlang:map_size(_@48)) == 2 -> begin
              case _@51 of
                (_@51) when (erlang:is_integer(_@51)) -> typecheck
              end,
              case _@52 of
                (_@52) when (erlang:is_integer(_@52)) -> typecheck
              end
            end
          end,
          case _@49 of
            (_@49) when (erlang:is_integer(_@49)) -> typecheck
          end,
          case _@50 of
            (_@50) when (erlang:is_float(_@50)) -> typecheck
          end
        end
      end
```

### CODE REVIEW

**Comment by drathier** [comment]
Didn't realize quite how horrible the error messages for this would be, so I'm working on making them more friendly now by manually calling `erlang:error` instead of relying on the built-in missing case match errors.

**Comment by nwolverson** [comment]
This looks good in principle, not stepped through the code entirely but seems to work out nicely that the erlang types are attached to the functions, so good place to locate this code. 

Not entirely sure on if this should always be generated or not, and I'm minded to change the terminology from "safe" - what do you think of "checked"? The point is that run time type-checking of arguments is performed, safety sounds to me like an internal property

**Comment by drathier** [comment]
It would be nice to have a shorter suffix than `@checkedps`, but I'm not opposed to changing `@safeps`.

Codegen for this could be behind a cli flag, or just generated for non-dependency files, I don't mind either as long as it's easy to set and forget. Is compilation speed an issue for you as it is?

**Comment by drathier** [comment]
Generated some error messages now. Here's a snippet of the generated type error code:

```
        (#{wooo:=_@50, yay:=_@51, abc:=_@52, arr:=_@53, boolie:=_@54}) when (erlang:map_size(_@49)) == 5 -> begin
          case _@50 of
            (#{wint:=_@55, wont:=_@56}) when (erlang:map_size(_@50)) == 2 -> begin
              case _@55 of
                (_@55) when (erlang:is_integer(_@55)) -> typecheck;
                (_) -> (erlang:error(<<"purerl runtime ffi type error: testfn->0(_@36).thingy.wooo.wint is not an integer"/utf8>>))
              end,
              case _@56 of
                (_@56) when (erlang:is_integer(_@56)) -> typecheck;
                (_) -> (erlang:error(<<"purerl runtime ffi type error: testfn->0(_@36).thingy.wooo.wont is not an integer"/utf8>>))
              end
            end;
            (#{wint:=_@55, wont:=_@56}) -> (erlang:error(<<"purerl runtime ffi type error: testfn->0(_@36).thingy.wooo failed map_size check; there's too many fields in this record"/utf8>>));
            (_) -> (erlang:error(<<"purerl runtime ffi type error: testfn->0(_@36).thingy.wooo is missing at least one field"/utf8>>))
```

**Comment by nwolverson** [comment]
I merged this, it is now behind a flag, and I used `@checked` suffix

**Pull request merged**
